{
	"version": 1480859846,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/greybackbg-sheet0.png",
		"images/nextbit-sheet0.png",
		"images/mainp2b-sheet0.png",
		"images/mainp2b-sheet1.png",
		"images/kebos1-sheet0.png",
		"images/kebos1-sheet1.png",
		"images/troy1-sheet0.png",
		"images/troy1-sheet1.png",
		"images/cloister1-sheet0.png",
		"images/cloister1-sheet1.png",
		"images/mainp1-sheet0.png",
		"images/mainp1-sheet1.png",
		"images/flash1-sheet0.png",
		"images/tristen1-sheet0.png",
		"images/nathan1-sheet0.png",
		"images/mainp2-sheet0.png",
		"images/mainp2-sheet1.png",
		"images/onsa1-sheet0.png",
		"images/fervest1-sheet0.png",
		"images/aaron1-sheet0.png",
		"images/aaron1-sheet1.png",
		"images/talbot-sheet0.png",
		"images/choicebutton1-sheet0.png",
		"images/choicebutton2-sheet0.png",
		"images/choicebutton3-sheet0.png",
		"images/choicebutton4-sheet0.png",
		"images/personposition1-sheet0.png",
		"images/bgdisp-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/playgame-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/nextchapter-sheet0.png",
		"images/erase1-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/itemsprite-sheet0.png",
		"images/generateloot-sheet0.png",
		"images/meleebuttonp1-sheet0.png",
		"images/energybuttonp1-sheet0.png",
		"images/healthbuttonp1-sheet0.png",
		"images/bg-sheet0.png",
		"images/p2hp-sheet0.png",
		"images/dodgebuttonp1-sheet0.png",
		"images/blockbuttonp1-sheet0.png",
		"images/battleevent-sheet0.png",
		"images/rand-sheet0.png",
		"images/turnsummary-sheet0.png",
		"images/turnsummary-sheet1.png",
		"images/focusbuttonp1-sheet0.png",
		"images/statbackb-sheet0.png",
		"images/aimode-sheet0.png",
		"images/p1focusboost-sheet0.png",
		"images/hpapr1-sheet0.png",
		"images/p1elementeffect-sheet0.png",
		"images/p1elementeffect-sheet1.png",
		"images/helpbox-sheet0.png",
		"images/helpbutton-sheet0.png",
		"images/p2party1face-sheet0.png",
		"images/p2party1face-sheet1.png",
		"images/p2party1face-sheet2.png",
		"images/p1party2face-sheet0.png",
		"images/finn1-sheet0.png",
		"images/talbot1-sheet0.png",
		"images/finnd1-sheet0.png",
		"images/tag1-sheet0.png",
		"images/fastforwardbit-sheet0.png",
		"media/attack1.m4a",
		"media/attack1.ogg",
		"media/attack2.m4a",
		"media/attack2.ogg",
		"media/attack3.m4a",
		"media/attack3.ogg",
		"media/attack4.m4a",
		"media/attack4.ogg",
		"media/dash noise.m4a",
		"media/dash noise.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/fireball1.m4a",
		"media/fireball1.ogg",
		"media/fireball2.m4a",
		"media/fireball2.ogg",
		"media/fireball3.m4a",
		"media/fireball3.ogg",
		"media/flame1.m4a",
		"media/flame1.ogg",
		"media/flame2.m4a",
		"media/flame2.ogg",
		"media/flashstep.m4a",
		"media/flashstep.ogg",
		"media/fly.m4a",
		"media/fly.ogg",
		"media/flying.m4a",
		"media/flying.ogg",
		"media/healing.m4a",
		"media/healing.ogg",
		"media/hey.m4a",
		"media/hey.ogg",
		"media/high laser.m4a",
		"media/high laser.ogg",
		"media/hit1.m4a",
		"media/hit1.ogg",
		"media/hit2.m4a",
		"media/hit2.ogg",
		"media/hit3.m4a",
		"media/hit3.ogg",
		"media/hop.m4a",
		"media/hop.ogg",
		"media/jump1.m4a",
		"media/jump1.ogg",
		"media/jump2.m4a",
		"media/jump2.ogg",
		"media/kabooom.m4a",
		"media/kabooom.ogg",
		"media/large jump.m4a",
		"media/large jump.ogg",
		"media/laser.m4a",
		"media/laser.ogg",
		"media/launch.m4a",
		"media/launch.ogg",
		"media/lazy jump.m4a",
		"media/lazy jump.ogg",
		"media/little bomb drop.m4a",
		"media/little bomb drop.ogg",
		"media/little slash.m4a",
		"media/little slash.ogg",
		"media/loss.m4a",
		"media/loss.ogg",
		"media/loud faraway boom.m4a",
		"media/loud faraway boom.ogg",
		"media/loud flyby.m4a",
		"media/loud flyby.ogg",
		"media/mario jump.m4a",
		"media/mario jump.ogg",
		"media/minerals detected.m4a",
		"media/minerals detected.ogg",
		"media/noisy.m4a",
		"media/noisy.ogg",
		"media/note.m4a",
		"media/note.ogg",
		"media/ooer.m4a",
		"media/ooer.ogg",
		"media/overhead chopper.m4a",
		"media/overhead chopper.ogg",
		"media/plasma.m4a",
		"media/plasma.ogg",
		"media/possession.m4a",
		"media/possession.ogg",
		"media/pow.m4a",
		"media/pow.ogg",
		"media/powerup.m4a",
		"media/powerup.ogg",
		"media/punch.m4a",
		"media/punch.ogg",
		"media/quake.m4a",
		"media/quake.ogg",
		"media/raw boop.m4a",
		"media/raw boop.ogg",
		"media/raw laser.m4a",
		"media/raw laser.ogg",
		"media/robot deactivate.m4a",
		"media/robot deactivate.ogg",
		"media/rocket launch.m4a",
		"media/rocket launch.ogg",
		"media/scare chord.m4a",
		"media/scare chord.ogg",
		"media/select1.m4a",
		"media/select1.ogg",
		"media/select2.m4a",
		"media/select2.ogg",
		"media/select3.m4a",
		"media/select3.ogg",
		"media/selection.m4a",
		"media/selection.ogg",
		"media/single slash.m4a",
		"media/single slash.ogg",
		"media/splash.m4a",
		"media/splash.ogg",
		"media/squeal.m4a",
		"media/squeal.ogg",
		"media/squish.m4a",
		"media/squish.ogg",
		"media/squish2.m4a",
		"media/squish2.ogg",
		"media/steam1.m4a",
		"media/steam1.ogg",
		"media/strong force.m4a",
		"media/strong force.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/vaporise.m4a",
		"media/vaporise.ogg",
		"media/vent.m4a",
		"media/vent.ogg",
		"media/whuu zip.m4a",
		"media/whuu zip.ogg",
		"media/whuu zip2.m4a",
		"media/whuu zip2.ogg",
		"media/woof.m4a",
		"media/woof.ogg",
		"media/victory jingle.ogg",
		"media/sfx - forest noise.ogg",
		"media/end of the world.ogg",
		"media/mystic revival.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}